version: '3.8'

services:
  mariadb:
    image: ghcr.io/paradist/upw_dbs_mariadb:latest
    container_name: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    networks:
      - internal
    volumes:
      - /srv/upw/mysql:/var/lib/mariadb  
      - "./init_panel.sql:/docker-entrypoint-initdb.d/init.sql"

  redis:
    image: ghcr.io/paradist/upw_dbs_redis:latest
    container_name: redis
    restart: always
    networks:
      - internal
    volumes:
      - /srv/upw/redis:/data
  
  pterodactyl:
    image: ghcr.io/paradist/upw_pterodactyl:latest
    networks:
      - internal
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
networks:
  internal:
    driver: bridge

